services:
  prismaweb:
    image: "gurudohimalaia/prismaweb:latest"
    container_name: "PrismaWeb"

    restart: always

    ports:
      - "9030:8080"

    environment:
      PRISMA_API_URL: ${PRISMA_API_URL}
